# Generated by Django 4.2.1 on 2023-05-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('valor', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('id_solicitud_credito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Banquero',
            fields=[
                ('rol', models.CharField(max_length=20)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCreditoEmpresa',
            fields=[
                ('nombre_solicitante', models.CharField(max_length=20)),
                ('direccion_solicitante', models.CharField(max_length=50)),
                ('id_solicitud_credito_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('solicitud_credito_id_solicitud_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.solicitudcredito')),
            ],
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='nombre_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('carnet_identidad', models.CharField(max_length=11)),
                ('salario_total', models.IntegerField()),
                ('personas_sustento', models.IntegerField()),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('nombre_director', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('ganancia_anual', models.IntegerField()),
                ('cantidad_trabajadores', models.IntegerField()),
                ('ministerio', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=11)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
    ]
